# Created using wingetcreate

PackageIdentifier: Duplicati.Duplicati
PackageVersion: 2.0.6.1
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://updates.duplicati.com/beta/duplicati-2.0.6.1_beta_2021-05-03-x64.msi
  InstallerSha256: A67D9C1459C65356A1225EC5314F7F1D2FCBED634241A4DA8DA6EB4510DEA384
ManifestType: installer
ManifestVersion: 1.0.0
