PackageIdentifier: Microsoft.MouseWithoutBorder
PackageName: Microsoft Garage Mouse without Borders
Moniker: mousewithoutborders
PackageVersion: 2.2.1.327
Publisher: Microsoft Garage
Author: Microsoft
License: Copyright (c) Microsoft Corporation. All rights reserved.
MinimumOSVersion: 10.0.0.0
PackageUrl: https://aka.ms/mm
ShortDescription: Mouse without Borders (https://aka.ms/mm) is a product that makes you the captain of your computer fleet by allowing you to control up to four computers from a single mouse and keyboard.
Tags:
- remote
- remotemachine
- remote machine
- mice
- mouse
- mice without border
- mouse without border
InstallerType: msi
Installers:
- Architecture: x86
  InstallerUrl: https://download.microsoft.com/download/6/5/8/658AFC4C-DC02-4CB8-839D-10253E89FFF7/MouseWithoutBordersSetup.msi
  InstallerSha256: 52ee7f6ddcd934ac50c937db06820e7ea6cb1a3908c6431b8b0bcb1e641712cb
  ProductCode: "{D3BC954F-D661-474C-B367-30EB6E56542E}"
PackageLocale: en-US
ManifestType: singleton
ManifestVersion: 1.0.0
