# Created using wingetcreate

PackageIdentifier: RingCentral.RingCentral
PackageVersion: 21.2.20.1756
PackageLocale: en-US
Publisher: RingCentral
PackageName: RingCentral
License: copyright (c) ringcentral
ShortDescription: Team messaging, video meetings, and a business phone.
ManifestType: defaultLocale
ManifestVersion: 1.0.0
