# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: ElectronicArts.EADesktop
PackageVersion: 12.0.92.4925
MinimumOSVersion: 10.0.0.0
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2010Redist-x86
    MinimumVersion: 10.0.40219
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
    MinimumVersion: 14.28.29325.2
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x86
    MinimumVersion: 14.28.29325.2
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x86
    InstallerType: exe
    InstallerUrl: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EADesktopInstaller.exe
    InstallerSha256: e2a4d1c8daffdf7395146cd6a92f6f03bb8b575b5e293e74530379a48a7d79f7
    InstallerSwitches:
      Custom: ACCEPT=YES
      Silent: /silent
      SilentWithProgress: /silent
    ProductCode: "{C2622085-ABD2-49E5-8AB9-D3D6A642C091}"
    Scope: machine
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
