# Created using wingetcreate

PackageIdentifier: SamuelRodberg.MinimalADBandFastboot
PackageVersion: 1.4.3
PackageLocale: en-US
Publisher: Samuel Rodberg
PackageName: Minimal ADB and Fastboot
License: None
ShortDescription: Minimal ADB and Fastboot Setup
ManifestType: defaultLocale
ManifestVersion: 1.0.0
