# Automatically updated by the winget bot at 2021/Jun/04
PackageIdentifier: BitSum.ProcessLassoBeta
PackageVersion: 10.1.0.33
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://dl.bitsum.com/files/beta/processlassosetup64.exe
  InstallerSha256: AF35CD004406E4F18F5EB74ACE094F391C22679A17F2511A9044353EE9D14CDE
ManifestType: installer
ManifestVersion: 1.0.0
