# Automatically updated by the winget bot at 2021/Jun/03
PackageIdentifier: SmartSoft.SmartFTP
PackageVersion: 9.0.2851.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://www.smartftp.com/get/SmartFTP64.msi
  InstallerSha256: 8D24E510B7B7AE88CF0714B4FFA14B8275778EBB0440A68D618A98F99D72E41C
  ProductCode: "{AEE0EDF3-E0B8-4DFC-A89C-934C359CF7EB}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
