# Automatically updated by the winget bot at 2021/Jun/03
PackageIdentifier: Cisco.WebexTeams
PackageVersion: 41.6.0.19119
InstallerType: msi
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/Webex.msi
  InstallerSha256: 4A5AFD33AF0B3456BEC3989A1E0F6392E1D34D560FA16D2B26BBF9E20102B5FE
  ProductCode: "{3BE6E5B5-AECB-53FC-A994-482829575706}"
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://binaries.webex.com/WebexTeamsDesktop-Windows-Gold/Webex_x86.msi
  InstallerSha256: BA06BEDA1EDEC0A204047E59CD3E4E48C116CE2D55913A318FF219BFA6343E46
  ProductCode: "{63600699-331E-5650-BFA0-5EA01B501F96}"
ManifestType: installer
ManifestVersion: 1.0.0
