# Created using wingetcreate

PackageIdentifier: Google.ChromeEnterprise
PackageVersion: 68.94.77
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7BD41AFA02-5E06-BDE4-D55C-B81F7E66AC5B%7D%26lang%3Den%26browser%3D4%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dtrue%26ap%3Dx64-stable-statsdef_0%26brand%3DGCEA/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: EDC0EC11CA98B20D230F98ACB8DA00A86EFA92EC90ED510D0ED2746061ED777F
  ProductCode: '{B6E20433-9CA8-39D7-93CD-7191D79C0A6C}'
ManifestType: installer
ManifestVersion: 1.0.0
