# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.0.0.schema.json
PackageIdentifier: Tutanota.Tutanota
PackageVersion: 3.84.0
MinimumOSVersion: 10.0.0.0
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: neutral
    InstallerType: nullsoft
    InstallerUrl: https://mail.tutanota.com/desktop/tutanota-desktop-win.exe
    InstallerSha256: 9040336A8CA0F704582943A8A2891BEDB8BB769EA5B62CBA91BC32CF8E888E84
    Scope: user
    InstallerLocale: en-US
    UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
