# Created using wingetcreate

PackageIdentifier: Glimpse.Glimpse
PackageVersion: 0.2.0
MinimumOSVersion: 10.0.0.0
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: msi
  InstallerUrl: https://github.com/glimpse-editor/Glimpse/releases/download/v0.2.0/glimpse-0.2.0-x64.msi
  InstallerSha256: 420DBBE11FEF2A1D741083EB72F99732B9AEC620D1D8274F9FB7A30E650030FF
  UpgradeBehavior: install
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  InstallerUrl: https://github.com/glimpse-editor/Glimpse/releases/download/v0.2.0/glimpse-0.2.0-i686.msi
  InstallerSha256: 2163403CA13D27BE399B7FC1348719B2A9A4DDC4BC8C4B00AA8EDD608BACFDBD
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
