# Automatically updated by the winget bot at 2021/Jun/03
PackageIdentifier: Google.ChromeBeta
PackageVersion: 68.104.49192
MinimumOSVersion: 10.0.0.0
FileExtensions:
- html
- htm
- url
Protocols:
- http
- https
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise64.msi
  InstallerSha256: 34301276E138B5CDCE3596006FCB7F5F660176D0075C90CC89B06E850B813B58
  ProductCode: "{3C1EEA75-E63E-3564-A90E-A9EE039E5F87}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: msi
  InstallerUrl: https://dl.google.com/tag/s/dl/chrome/install/beta/googlechromebetastandaloneenterprise.msi
  InstallerSha256: 75FEDF4976CF32BC9A01AF8609A09E3395C226281786CCA68EBE9A827B062248
  ProductCode: "{ACC0FCF9-4547-3F1C-8951-04E8C9606268}"
  Scope: machine
  InstallerLocale: en-US
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.0.0
